spring.datasource.url=jdbc:postgresql://localhost:5432/diary_db
spring.datasource.username=postgres
spring.datasource.password=Kissme0313
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Thymeleafテンプレートの設定
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false
